### ISSUE TITLE
Noty or other notification libs

### ISSUE THREAD

**Issue by michelep** [StartBootstrap/startbootstrap-agency#156]
Thanks for your great work ! However i'm getting some troubles let Noty (https://ned.im/noty) works. I t display notifications but seems that there is something that interfere with timings and clicks. Any hints how to get any notification script working ? I need that for Cookie-related alerts (GDPR compliants)...

Thanks!

**Comment by davidtmiller** [comment]
There isn't a whole lot of custom JS with this theme, so it could have something to do with interfering with Bootstrap itself. I'd see if there is anything in the issues for Noty that references interferences with Bootstrap's JS files. Otherwise it could be interfering with some other plugin used, but I am not 100% sure.
