### ISSUE TITLE
Changes over the file bootstrap.css are not reflected.

### ISSUE THREAD

**Issue by davidberco** [StartBootstrap/startbootstrap-agency#185]
All the changes I made over the files inside the SCSS folder are effectively taken place on the website. BUT, if I change some css attributes inside the file **bootstrap.css** are not reflected. I notice that when I'm running ``` gulp ``` on the command line, the file bootstrap.css resets to the original version. Inside the gulpfile.js there is a "clean vendor" function. If I comment that function, the ```gulp``` command doesn't work. 
How can I permanent retain this changes over the files inside the vendor folder? 
thanks in advance for your help.
Great work, @davidtmiller and the rest of contributors. cheers!

**Comment by davidtmiller** [comment]
Generally speaking it's not a good idea to edit the core Bootstrap files, otherwise you would be stuck with that version for all time. The best way to change anything in this case would be to overwrite the Bootstrap CSS using your own custom CSS - that way if Bootstrap updates their version then it is easy to drop into the project.

The vendor function in the gulpfile has a task attached to it, and you would need to remove all of the calls of that function in order to make the gulpfile work again if that was something you wanted to do.
