### ISSUE TITLE
Contact Form always fails

### ISSUE THREAD

**Issue by bondar-artem** [StartBootstrap/startbootstrap-agency#194]
I can't make the form working. It always fails whatever I do.

I have read the other closed issues with the links to StackOverflow how to set up php mailer but nothing works.

Even when I comment all code in contact_me.php and just leave there "return true", it s showing error on the page "Sorry it seems that my mail server is not responding. Please try again later!"
How come? Why?

**Comment by davidtmiller** [comment]
Are you running the form locally or on a live server? If you're running the form on a live server it probably has something to do with the version of PHP that is running in the server environment, or the server environment not having a mail handler. Sometimes there are permissions on the server that prevents a form from sending.

If you have tried everything, I would try using a service like formspree in order to handle the sending of the contact form.

**Comment by bondar-artem** [comment]
@davidtmiller 
I have tried locally and  deployed it to google cloud. Nothing worked.
And as I have mentioned, in PHP file I just said "return true" and that's it. Nothing else. And I expect that my fronted app should not show any errors that something is wrong. But it still showing the error even if I simulate success email send. So something weird with contact_me.js I guess, not with the php mailer
